// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:e83864a35d49c7dce0c9df2ec696e13182b6a0b341e7ec2295640628b3d26b6f",
    "semanticFingerprint": "typebox-value-hash-v1:fe01cffedd7deba0",
    "defaultSettings": {
        "projectOverrides": true
    }
} as const;

export default artifact;
